apiVersion: v1
kind: ConfigMap
metadata:
  name: gto-load-balance-config
data:
  nginx.conf: |
    user nginx;
    worker_processes  3;
    error_log  /var/log/nginx/error.log;
    events {
      worker_connections  10240;
    }
    http {
      log_format  main
              '[$time_iso8601] '
              'remote_addr:$remote_addr '
              'method:$request_method '
              'uri:$request_uri '
              'host:$host '
              'status:$status '
              'request_time:$request_time';

      limit_req_zone $binary_remote_addr zone=backend:10m rate=100r/s;
      limit_req_status 429;

      access_log	/var/log/nginx/access.log main;

      server {
          listen 80 default_server;
          root /usr/local/app;

          server_name  _;

          location / {
            limit_req zone=backend;
            proxy_pass http://backend;
            proxy_http_version 1.1;
          }
      }

      upstream backend {
        server localhost:8080;
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gto-nginx-scrapper-config
data:
  prometheus-nginxlog-exporter.hcl: |
    namespace "gto-backend" {
      format = "[$time_iso8601] remote_addr:$remote_addr method:$request_method uri:$request_uri host:$host status:$status request_time:$request_time"

      source {
        files = [
          "/var/log/nginx/access.log"
        ]
      }

      labels {
        app = "gto-backend"
        environment = "dev"
      }

      histogram_buckets = [.005, .01, .025, .05, .1, .25, .5, 1, 2.5, 5, 10]
    }
