apiVersion: v1
kind: ConfigMap
metadata:
  name: gto-db-config
  labels:
    app: gto
    tier: db
    kind: config
data:
  POSTGRES_DB: gto-db
  POSTGRES_USER: gto-db-user
  POSTGRES_PASSWORD: gto-db-password
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gto-db-metrics-config
  labels:
    app: gto
    tier: db-metrics
    kind: config
data:
  DATA_SOURCE_URI: localhost:5432?sslmode=disable
  DATA_SOURCE_USER: gto-db
  DATA_SOURCE_PASS: gto-db-password
  PG_EXPORTER_WEB_LISTEN_ADDRESS: :9100
