apiVersion: v1
kind: ConfigMap
metadata:
  name: gto-db-config
  labels:
    app: gto
    tier: db
    kind: config
data:
  POSTGRES_DB: gto-db
  POSTGRES_USER: gto-db-user
  POSTGRES_PASSWORD: gto-db-password
