apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gto-db
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: gto
      tier: db
      kind: db
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/should_be_probed: "true"
      labels:
        app: gto
        tier: db
        kind: db
    spec:
      containers:
        - name: postgres
          image: postgres:12.2
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          resources:
            limits:
              cpu: "500m"
              memory: "2Gi"
            requests:
              cpu: "50m"
              memory: "200Mi"
          envFrom:
            - configMapRef:
                name: gto-db-config
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: gto-db
        - name: postgres-metrics
          image: wrouesnel/postgres_exporter:v0.8.0
          imagePullPolicy: IfNotPresent
          args:
            - "--disable-settings-metrics"
          resources:
            limits:
              cpu: "10m"
              memory: "10Mi"
          envFrom:
            - configMapRef:
                name: gto-db-metrics-config
          ports:
            - name: metrics-db
              containerPort: 9100
      volumes:
        - name: gto-db
          persistentVolumeClaim:
            claimName: gto-db-claim
---
apiVersion: v1
kind: Service
metadata:
  name: gto-db-svc
  labels:
    app: gto
    tier: db
    kind: service
spec:
  type: ClusterIP
  ports:
    - name: gto-db-svc
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: gto
    tier: db
    kind: db
