kind: PersistentVolume
apiVersion: v1
metadata:
  name: gto-db-volume
  labels:
    app: gto
    tier: db
    kind: volume
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gto-db-claim
  labels:
    app: gto
    tier: db
    kind: claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
