---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gto-db-claim
  labels:
    app: gto
    tier: db
    kind: claim
spec:
  storageClassName: hcloud-volumes
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
