---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana-volume-claim
  namespace: monitoring
  labels:
    app: grafana
    tier: monitoring
    kind: claim
spec:
  storageClassName: hcloud-volumes
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prometheus-volume-claim
  namespace: monitoring
  labels:
    app: prometheus
    tier: monitoring
    kind: claim
spec:
  storageClassName: hcloud-volumes
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
