kind: PersistentVolume
apiVersion: v1
metadata:
  name: monitoring-volume
  namespace: monitoring
  labels:
    scope: monitoring
    tier: storage
    kind: volume
spec:
  storageClassName: hcloud-volumes
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana-volume-claim
  namespace: monitoring
  labels:
    app: grafana
    tier: monitoring
    kind: claim
spec:
  storageClassName: hcloud-volumes
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      scope: monitoring
      tier: storage
      kind: volume
  resources:
    requests:
      storage: 10Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prometheus-volume-claim
  namespace: monitoring
  labels:
    app: prometheus
    tier: monitoring
    kind: claim
spec:
  storageClassName: hcloud-volumes
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      scope: monitoring
      tier: storage
      kind: volume
  resources:
    requests:
      storage: 10Gi
