apiVersion: apps/v1
kind: Deployment
metadata:
  name: gto-front-deployment
spec:
  selector:
    matchLabels:
      app: gto
      tier: frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: gto
        tier: frontend
    spec:
      containers:
        - name: gto-front-container
          image: docker.pkg.github.com/gtoru/front/front
          ports:
            - containerPort: 80
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "250m"
              memory: "64Mi"
      imagePullSecrets:
        - name: gto-regcred
---
apiVersion: v1
kind: Service
metadata:
  name: gto-front-svc
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: gto
    tier: frontend
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gto-front-ingress
spec:
  rules:
    - host: gto.kohea.tel
      http:
        paths:
          - path: /
            backend:
              serviceName: gto-front-svc
              servicePort: 80
