name: "Deploy infrastructure manual trigger"

on:
  issue_comment:
    types:
      - created
      - edited

jobs:
  deploy_dev_job:
    runs-on: ubuntu-latest
    if: github.event.comment.user.login == 'madetara' && github.event.comment.body == 'Deploy Infra'
    name: Deploy Infrastructure
    steps:
      - name: Notify
        uses: jungwinter/comment@v1
        id: create
        with:
          type: create
          body: "Deploying Infrastructure"
          issue_number: ${{ github.event.issue.number }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
      - name: Configure k8s
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: 'mkdir ~/.kube && echo "$KUBECONFIG" > ~/.kube/config'
      - name: Set infra namespace for kubectl
        run: kubectl config set-context --current --namespace=infra
      - name: Apply Prometheus configuration
        run: |
          kubectl apply -f config/dev/infra/prometheus/clusterRole.yaml
          kubectl apply -f config/dev/infra/prometheus/config.yaml
          kubectl apply -f config/dev/infra/prometheus/deployment.yaml
