name: "Deploy infrastructure services"

on:
  push:
    branches:
      - master
    paths:
      - config/infra/**/*
      - .github/workflows/deploy-infra.yaml

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v2
      - name: Configure k8s
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: 'mkdir ~/.kube && echo "$KUBECONFIG" > ~/.kube/config'
      - name: Set system namespace for kubectl
        run: kubectl config set-context --current --namespace=kube-system
      - name: Apply kube-state configuration
        run: |
          kubectl apply -f config/infra/kube-state/clusterRole.yaml
          kubectl apply -f config/infra/kube-state/deployment.yaml
      - name: Set infra namespace for kubectl
        run: kubectl config set-context --current --namespace=monitoring
      - name: Prepare PVC
        run: kubectl apply -f config/infra/volume.yaml
      - name: Apply Prometheus configuration
        run: |
          kubectl apply -f config/infra/prometheus/clusterRole.yaml
          kubectl apply -f config/infra/prometheus/config.yaml
          kubectl apply -f config/infra/prometheus/deployment.yaml
      - name: Apply Grafana configuration
        run: |
          kubectl apply -f config/infra/grafana/datasource.yaml
          kubectl apply -f config/infra/grafana/deployment.yaml
