name: "Deploy cluster manual trigger"

on:
  issue_comment:
    types:
      - created
      - edited

jobs:
  deploy_dev_job:
    runs-on: ubuntu-latest
    if: github.event.comment.user.login == 'madetara' && github.event.comment.body == 'Deploy DEV'
    name: Deploy DEV
    steps:
      - name: Notify
        uses: jungwinter/comment@v1
        id: create
        with:
          type: create
          body: "Deploying DEV cluster"
          issue_number: ${{ github.event.issue.number }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2
      - name: Configure k8s
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: 'mkdir ~/.kube && echo "$KUBECONFIG" > ~/.kube/config'
      - name: Set gto-dev namespace for kubectl
        run: kubectl config set-context --current --namespace=gto-dev
      - name: Add access-token as secret
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: kubectl get secrets gto-regcred || kubectl create secret docker-registry gto-regcred --namespace=gto-dev --docker-server=docker.pkg.github.com --docker-username=gtoru --docker-password=$ACCESS_TOKEN
      - name: Apply DB configuration
        run: |
          kubectl apply -f config/dev/db/configmap.yaml 
          kubectl apply -f config/dev/db/volume.yaml
          kubectl apply -f config/dev/db/service.yaml
      - name: Apply Front configuration
        run: kubectl apply -f config/dev/front.yaml
      - name: Apply Back configuration
        run: kubectl apply -f config/dev/backend.yaml
