name: "Deploy infrastructure services"

on:
  push:
    branches:
      - master
    paths:
      - config/dev/infra/**/*

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v2
      - name: Configure k8s
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: 'mkdir ~/.kube && echo "$KUBECONFIG" > ~/.kube/config'
      - name: Set infra namespace for kubectl
        run: kubectl config set-context --current --namespace=infra
      - name: Apply Prometheus configuration
        run: |
          kubectl apply -f config/infra/prometheus/clusterRole.yaml
          kubectl apply -f config/infra/prometheus/config.yaml
          kubectl apply -f config/infra/prometheus/deployment.yaml
