name: "Deploy Kubernetes DEV cluster"

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/deploy-dev.yaml
      - config/dev/**/*

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v2
      - name: Configure k8s
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: 'mkdir ~/.kube && echo "$KUBECONFIG" > ~/.kube/config'
      - name: Set gto-dev namespace for kubectl
        run: kubectl config set-context --current --namespace=gto-dev
      - name: Add access-token as secret
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: kubectl get secrets gto-regcred || kubectl create secret docker-registry gto-regcred --namespace=gto-dev --docker-server=docker.pkg.github.com --docker-username=gtoru --docker-password=$ACCESS_TOKEN
      - name: Apply DB configuration
        run: |
          kubectl apply -f config/dev/db/configmap.yaml 
          kubectl apply -f config/dev/db/volume.yaml
          kubectl apply -f config/dev/db/service.yaml
      - name: Apply Front configuration
        run: kubectl apply -f config/dev/front.yaml
      - name: Apply Back configuration
        run: |
          kubectl apply -f config/dev/backend/balancer.yaml
          kubectl apply -f config/dev/backend/server.yaml
      - name: Apply balancer
        run: kubectl apply -f config/dev/ingress.yaml
